# Generated by Django 4.2.3 on 2023-07-19 08:12

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('legal_address', models.CharField(max_length=200)),
                ('physical_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            bases=(models.Model, web.models.ID),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
